# Generated by Django 5.0.dev20230526101626 on 2023-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('emp_no', models.CharField(max_length=200, null=True)),
                ('salary', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
